# Generated by Django 3.0.4 on 2020-04-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards_app', '0002_remove_calendar_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='post_image',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='set_date',
        ),
    ]
